[package]
name = "libtor"
version = "44.5.1+0.4.4.5"
authors = ["Alekos Filini <alekos.filini@gmail.com>"]
license = "MIT"
homepage = "https://github.com/MagicalBitcoin/libtor"
repository = "https://github.com/MagicalBitcoin/libtor"
documentation = "https://docs.rs/libtor/"
description = "Bundle and run Tor inside your own project"
keywords = ["tor", "daemon"]
readme = "README.md"

[dependencies]
libtor-sys = { git= "https://github.com/Sifir-io/libtor-sys.git" }
libtor-derive = "0.1"
log = "^0.4"

[features]
vendored-openssl = ["libtor-sys/vendored-openssl"]
